### ISSUE TITLE
collectionview optional?

### ISSUE THREAD

**Issue by sukhanovevgeniy96** [DenTelezhkin/DTCollectionViewManager#32]
Hello! Why is collection view in DTCollectionViewManageable optional? It will be better if it is  nonoptional value like in DTTableViewManageable

```
public protocol DTTableViewManageable : class
{
    /// Table view, that will be managed by DTTableViewManager
    var tableView : UITableView! { get }
}
```

```
public protocol DTCollectionViewManageable : class
{
    /// Collection view, that will be managed by DTCollectionViewManager
    var collectionView : UICollectionView? { get }
}
```

**Comment by DenHeadless** [comment]
Hey!
The reasons are actually funny - initially i was aligning those protocols with UICollectionViewController and UITableViewController, which had different interfaces in Swift 2 and 3, `tableView` was implicitly unwrapped and `collectionView` was optional. 

In Xcode 10 however, both are implicitly unwrapped, and collectionView is no longer optional. Undoing this protocol requirement though would be a breaking change for all users of the framework, so to work around this issue I created one additional protocol `DTCollectionViewNonOptionalManageable`, which you can use for non-optional collectionView. Name is definitely ugly, ideally i would want to actually have one protocol, but I don't want to make a breaking release just to change one protocol name.

Can you leave this issue open for now, please?

**Comment by mrJ0hn** [comment]
> Hey!
> The reasons are actually funny - initially i was aligning those protocols with UICollectionViewController and UITableViewController, which had different interfaces in Swift 2 and 3, `tableView` was implicitly unwrapped and `collectionView` was optional.
> 
> In Xcode 10 however, both are implicitly unwrapped, and collectionView is no longer optional. Undoing this protocol requirement though would be a breaking change for all users of the framework, so to work around this issue I created one additional protocol `DTCollectionViewNonOptionalManageable`, which you can use for non-optional collectionView. Name is definitely ugly, ideally i would want to actually have one protocol, but I don't want to make a breaking release just to change one protocol name.
> 
> Can you leave this issue open for now, please?

Thank you very much!

**Comment by DenTelezhkin** [comment]
Hi!

I've replaced `DTCollectionViewNonOptionalManageable` protocol with additional property on `DTCollectionViewManageable` protocol in https://github.com/DenTelezhkin/DTCollectionViewManager/commit/ecd9c31ba11b3b7784c4e43e0ab13b600815066c. Once released, `DTTableViewManager` and `DTCollectionVIewManager` will be consistent on optionality of table/collection views, and will not rely on UIKit or Swift changes.

However, specifically for `DTCollectionViewManager`, it's a breaking change, that will lead to crashes if code is not updated(`collectionView` property in protocol is now implicitly unwrapped instead of optional). Because of that I will be rolling this functionality in the major release somewhere in the fall, after iOS 13 release with other features of iOS 13 and Xcode 11.
