### ISSUE TITLE
can you set more than one `configure` block for a cell class?

### ISSUE THREAD

**Issue by skydivedan** [DenTelezhkin/DTCollectionViewManager#33]
I was trying to do something where I was calling `configure` twice on the same cell class.

Looking at the `configure` code, it calls a routine named `appendReaction`,  which made me think that I could do this. Ordering of the two blocks doesn't matter. But I noticed, while stepping through, that  `delegateWasReset` gets called when the reaction is appended. The end result is that the second  `configure` block is not called.

Anyway, just wondering if 2 configure blocks can be added to the same cell-class, and if so, how? If not, then I just need to know that.

**Comment by skydivedan** [comment]
nevermind, found the answer myself (just minutes after posting this question). only one reaction with the same signature is performed.

**Comment by DenHeadless** [comment]
Hi!

So, indeed, only first reaction is getting called by design, however framework does not stop you from registering more than one reaction per cell type, which is actually a small design flaw, since second and subsequent closures will never get called. I was recently suggested by one of our team members to support multiple reaction per cell type and introduce a system which could allow you to subscribe/unsubscribe from those reactions using mechanism similar to iOS NotificationCenter observers. 

I'm not sold on this idea yet, since it would require token management system and I'm not sure it's worth the effort. But anyway, i'm curious to hear about your use-case, why do you want multiple configuration closures, is there some specific reason where one closure is not enough?

**Comment by skydivedan** [comment]
Well, it was a protocol-extension thing.
I wrote a common routine to do a `configure` block that could be used by a
number of classes.

Then later, in a specific class, I tried to add on another `configure` for
some very specific behavior.
I can work around it. I just didn't understand that I couldn't do that at
the time... probably just because the function was named `append`, I just
figured it would cycle through the full array.

But now that I know, it's not a big deal.

**Comment by DenHeadless** [comment]
Thanks!

I would like to keep this issue open, if you don't mind, at some point I would like to address this one way or another.

**Comment by DenTelezhkin** [comment]
After some considerations, I decided to leave everything as it is and not change current behavior. Implementing a comparing and analyzing system for events and signatures is more complex than I want this framework to be. I've added notes to readmes about current behavior to hopefully be clearer. 

Since open-source requires additional time when compared to daily job, it's important to choose battles carefully. Unfortunately, this seems like one of the battles, that is better to retreat from =)
