### ISSUE TITLE
Access to previous model using CoreDataStorage

### ISSUE THREAD

**Issue by sukhanovevgeniy96** [DenTelezhkin/DTCollectionViewManager#34]
Hi, could you help me, I want to get access to previous model when I use coredata as storage. 
I need get access to previous model in manager.configure closure

**Comment by DenTelezhkin** [comment]
Hi!

Unfortunately, it's not that easy to make this happen, since when configuration block is run, previous data model may not be in storage anymore.

One thing you could do is cache model on `UICollectionViewCell` level, but there are no guarantees about indexPaths, since new cells are taken from reuse pool of cells. You could do it like so:

```swift
class UpdatedCell: UICollectionViewCell, ModelTransfer {
    var currentModel: Model? {
        willSet {
            if let currentModel = currentModel {
                 print("Updated model from \(currentModel) to \(newValue)")
            }
        }
    }

    func update(with model: Model) {
        currentModel = model
    }
}
```

On the other hand, If you want to somehow update new model in CoreData from the old one, I suggest doing that on CoreData level when you import data there, not on UI representation level.
